### ISSUE TITLE
Need more detailed readme

### ISSUE THREAD

**Issue by rsmything** [amatsuda/himl#2]
Hello, how to use Himl in the next cases?

```
<div class="head">
  <h1>
    Does it work?
  <h1>Does it work?
<body>
  <ul>
    <%= @users.each do |user| %>
      <li>
        <=% user.name %>
      <a><=% user.surname %> // does it work?
    // <% end %> Does it work without END?
```

**Comment by amatsuda** [comment]
Documentation patches are always welcome!
Your questions may be answered in the tests, e.g.
https://github.com/amatsuda/himl/blob/e7a6731a3bbbd46799167bbf6c37f1c7ca609f99/test/himl_test.rb#L91-L142

**Comment by amatsuda** [comment]
BTW added some more examples at 375d5a47c00b7c7b594dd21f169259572ad52d1e.
Thanks for the feedback!
